/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "fatfs.h"
#include "rc522.h"
#include "stdio.h"
#include "string.h"
#include "stm32f4xx_hal.h"


char CardID[5];
char ret;
char MyCardID[5] = {108,220,219,130,233};

FATFS   	 fs;
FRESULT		res;
FIL    		file;
UINT br,i;
char buffer[1024];
char *ptr;
char strCardID[16];
char *token;
char PersonelInfo[5][20];
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0            (GUI_ID_USER + 0x00)
#define ID_TEXT_0            (GUI_ID_USER + 0x03)
#define ID_TEXT_1            (GUI_ID_USER + 0x04)
#define ID_TEXT_2            (GUI_ID_USER + 0x05)
#define ID_TEXT_3            (GUI_ID_USER + 0x06)
#define ID_TEXT_4            (GUI_ID_USER + 0x07)
#define ID_TEXT_5            (GUI_ID_USER + 0x08)
#define ID_TEXT_6            (GUI_ID_USER + 0x09)
#define ID_TEXT_7            (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "PersonelGecis", ID_FRAMEWIN_0, 120, 0, 200, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NAME:", ID_TEXT_0, 5, 29, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SICIL NO:", ID_TEXT_1, 5, 49, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "GOREVI:", ID_TEXT_2, 5, 69, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CARD ID:", ID_TEXT_3, 5, 89, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 61, 29, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 61, 49, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 61, 69, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 61, 89, 100, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'NAME:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePersonelGecis
*/
WM_HWIN CreatePersonelGecis(void);
WM_HWIN CreatePersonelGecis(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
char RFID_Card_Check(char *CardID)
{
	  if(MFRC522_Check((uint8_t*)CardID) == MI_OK)
	  {
		  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET);
		  return MI_OK;
	  }

		  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_RESET);
		  return MI_NOK;
}

char CheckDataBase(char *CardID)
{

	sprintf(strCardID, "%03d%03d%03d",CardID[0],CardID[1],CardID[2]);

	res = f_open(&file, "test.txt", FA_READ);
	  if(res == FR_OK)
	   {
		  res = f_read(&file, buffer, sizeof(buffer), &br);
		  if(res == FR_OK)
		  {
			  ptr = strstr(buffer, strCardID);
			  if(ptr)
			  {
				 token = strtok(ptr, "\t");
				 i = 0;
				 while(token != NULL)
				 {
					 sprintf(&PersonelInfo[i++][0], token);
					 if(i == 5) break;
					 token = strtok(NULL,"\t");
				 }
				 ptr = strchr(&PersonelInfo[4][0], '\r');
				 *ptr = 0;
			  }

		  }
		  else
		  {
			  f_close(&file);
			  return 0;
		  }
	   }
	  else
	  {
		  f_close(&file);
		  return 0;
	  }
	  f_close(&file);

	return 1;
}

U8 _acBuffer[1024];
static int _GetData(void * p, const U8 ** ppData, unsigned NumBytesReq, U32 Offset) {
    unsigned int NumBytesRead;
    f_lseek((FIL *) p, Offset); //Set file pointer to the required position
    /*
     * Read file function
     * FIL*     fp      -	Pointer to the file object
     * void*    buff    -	Pointer to data buffer
     * UINT     btr     -	Number of bytes to read
     * UINT*    br      -	Pointer to number of bytes read
     */
    f_read((FIL *) p, (void *) _acBuffer, NumBytesReq, &NumBytesRead); //Read data into buffer
    *ppData = (const U8 *) _acBuffer; //Set pointer to the buffer
    return NumBytesRead;
}

void RFID_Reader(){

	WM_HWIN hWin;
	TEXT_Handle		hText4,hText5,hText6,hText7;

	  ret = f_mount(&fs, "", 0);
	  if(ret != FR_OK)
	   {
	 	  while(1);
	   }

	  hWin = CreatePersonelGecis();

	  hText4 = WM_GetDialogItem(hWin, ID_TEXT_4);
	  hText5 = WM_GetDialogItem(hWin, ID_TEXT_5);
	  hText6 = WM_GetDialogItem(hWin, ID_TEXT_6);
	  hText7 = WM_GetDialogItem(hWin, ID_TEXT_7);

	while(1)
	{
		   ret = RFID_Card_Check(CardID);
		   if(ret == MI_OK)
		   {
			   if(CheckDataBase(CardID))
			   {
				   TEXT_SetText(hText4, &PersonelInfo[1][0]);
				   TEXT_SetText(hText5, &PersonelInfo[2][0]);
				   TEXT_SetText(hText6, &PersonelInfo[3][0]);
				   TEXT_SetText(hText7, &PersonelInfo[0][0]);

					res = f_open(&file, &PersonelInfo[4][0], FA_OPEN_EXISTING | FA_READ);
					if (res == FR_OK)
						GUI_BMP_DrawEx(_GetData, &file, 14, 60);
					f_close(&file);
			   }
		   }
		   HAL_Delay(500);
		   GUI_Exec();
	}
}

// USER END

/*************************** End of file ****************************/
